apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app:product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 192.168.3.32:32005/product-service:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: spring.data.mongodb.host
              value: {host-mongo}
            - name: spring.data.mongodb.port
              value: 27017
            - name: spring.data.mongodb.database
              value: product
            - name: application.jwt.publicKey
              value: file:{path}/public_key.der
            - name: spring.kafka.producer.bootstrap-servers
              value:
            - name: spring.kafka.consumer.bootstrap-servers
              value:
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  ports:
    - port: 8080
      name: product-service
      nodePort: 31516
      targetPort: 8080
  type: NodePort
  selector:
    app: product-service