spring:
  profiles:
    active: "dev"
  main:
    Profile-mode: "off"
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order
      auto-index-creation: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
server:
  port: 8082
  servlet:
    context-path: /order-service
application:
  jwt:
    publicKey: cert/public_key.der

---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
