spring:
  profiles:
    active: "dev"
  main:
    Profile-mode: "off"
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
  kafka:
    consumer:
      bootstrap-servers: 192.168.3.35:31528,192.168.3.35:31529,192.168.3.35:31530
    producer:
      bootstrap-servers: 192.168.3.35:31528,192.168.3.35:31529,192.168.3.35:31530
server:
  port: 8080
  servlet:
    context-path: /product-service
application:
  jwt:
    publicKey: cert/public_key.der

---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
